### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by brnl** [JeffyW/OctoPrint-ServerStats#2]
Tried installing it with the provided URL but it ended in errors:

> 2018-05-06 03:39:30,568   /home/pi/oprint/bin/python2 -m pip install https://github.com/JeffyW/OctoPrint-ServerStats/archive/master.zip
> 2018-05-06 03:39:36,631 > Collecting https://github.com/JeffyW/OctoPrint-ServerStats/archive/master.zip
> 2018-05-06 03:39:38,000 > Downloading https://github.com/JeffyW/OctoPrint-ServerStats/archive/master.zip
> 2018-05-06 03:39:44,230 > Complete output from command python setup.py egg_info:
> 2018-05-06 03:39:44,232 > Traceback (most recent call last):
> 2018-05-06 03:39:44,233 > File "<string>", line 1, in <module>
> 2018-05-06 03:39:44,234 > File "/tmp/pip-oM8DLz-build/setup.py", line 49, in <module>
> 2018-05-06 03:39:44,235 > plugin_additional_packages = [ psutil ]
> 2018-05-06 03:39:44,236 > NameError: name 'psutil' is not defined
> 2018-05-06 03:39:44,237 >
> 2018-05-06 03:39:44,239 > ----------------------------------------
> 2018-05-06 03:39:45,243 ! Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-oM8DLz-build/
> 2018-05-06 03:39:45,244 ! You are using pip version 9.0.3, however version 10.0.1 is available.
> 2018-05-06 03:39:45,245 ! You should consider upgrading via the 'pip install --upgrade pip' command.

Running PrusaPrint image (Octopi 0.15) with Octoprint 1.3.8.

Please let me know if you need more info, or if you're not going to fix this. :-)

**Comment by JeffyW** [comment]
So sorry about this bug (and that I let it sit so long).
I fixed this as well as added support for the Pi 3.
